[package]
name = "bentypingrust"
version = "0.1.0"
authors = ["Adrian Gose <adrian@gose.pw>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"
serenity = "0.8"
config = "0.9"
lazy_static = "1.4.0"